# Generated by Django 5.1.6 on 2025-03-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_profile_cv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="intro_video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_embed_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
