# Generated by Django 5.1.6 on 2025-03-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_alter_profile_youtube_embed_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="youtube_embed_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Enter the full YouTube URL, e.g., https://youtu.be/3TGqlQxpuU0 or https://www.youtube.com/watch?v=3TGqlQxpuU0",
                max_length=500,
                null=True,
            ),
        ),
    ]
