# Generated by Django 5.1.6 on 2025-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_remove_profile_youtube_embed_url_profile_youtube_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Enter only the YouTube URL, e.g., https://www.youtube.com/embed/3TGqlQxpuU0",
                max_length=500,
                null=True,
            ),
        ),
    ]
