# Generated by Django 5.1.6 on 2025-03-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0006_remove_profile_youtube_url_profile_youtube_embed_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="youtube_embed_url",
        ),
    ]
