# Generated by Django 5.1.6 on 2025-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0007_remove_profile_youtube_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_bio",
            field=models.TextField(
                blank=True, help_text="A short version of your bio for the homepage"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="top_skills",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="portfolio_app.skill"
            ),
        ),
    ]
